### ISSUE TITLE
"No output locations found"

### ISSUE THREAD

**Issue by champagnealexandre** [david-j-lee/electron-inject-css#1]
hey I’m trying to use `electron-inject-css` and got the following error:

```
ERROR 0 output locations found.
No output locations found, nothing to do here.
```

any idea what might cause this?

thanks :-)

**Comment by david-j-lee** [comment]
What value are you providing for "Input dest for css file in unpacked asar."?

This tool unpacks the electron ASAR file and uses the provided value above to locate the folder in the unpacked asar to store your custom CSS file. This location would likely differ depending on what electron application you are trying to inject your CSS into.

I also noticed that the default value for that property is misleading, I will update that to reflect a directory instead of a file.

**Comment by champagnealexandre** [comment]
Just tried it again with a directory but I’m stuck at the HTML directory now.

Sorry I’m not used to electron development at all. Don’t really have time to debug this, thanks anyway for your help!
